name: Spring Boot CI

on:
  push:
    branches:
      - main
      - feature/docker-learning

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/springboot_db
          SPRING_DATASOURCE_USERNAME: springuser
          SPRING_DATASOURCE_PASSWORD: Spring@2026#Boot
        run: ./mvnw clean package